### ISSUE TITLE
jen.zerotask.net produces a 404

### ISSUE THREAD

**Issue by vringar** [SirWindfield/cargo-create#94]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
When clicking the link given on the project home page I can see no website.

**Expected behavior**

I would see the GitHub Pages/ the documentation of the project.

**Possible Solution**
Unfortunately I don't know enough about GH Pages or Vercel to suggest a fix.

**Additional context**

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/13276717/104943549-34d18b80-59b6-11eb-8c4f-0ffd2ef641ae.png">

**Comment by SirWindfield** [comment]
Should be up and running again!
